---
name: build

on:
  push:
    paths:
      - "**.rs"
      - "Cargo.toml"
      - "Cargo.lock"
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN: 1.74.0
  RUSTUP_TOOLCHAIN: stable

jobs:
  build:
    name: Compile and check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
          - target: x86_64-unknown-linux-musl
          - target: x86_64-apple-darwin
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: $RUSTUP_TOOLCHAIN
          override: true
          components: cargo, rustfmt, clippy

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run lints
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --verbose
