---
name: test

on:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install rust toolchain
        run: |
          rustup toolchain install
          rustup component add rustfmt
          rustup component add clippy

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run cargo check
        run: cargo check

      - name: Run linter
        run: cargo clippy -- -D warnings

      - name: Run unit tests
        run: cargo test --verbose
